<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/1/3
 * Time: 9:25
 */

namespace app\models;

use Yii;
use yii\base\Model;

/*yii\base\Model;
a base class provided by Yii,
commonly used to represent form data.
is used as a parent for model classes not associated with database tables
*/

class EntryForm extends Model
{
    public $name;
    public $email;

    /*
     * rules() returns a set of rules for validating the data
     * both the name and email values are required
     * the email data must be a syntactically valid email address
     */
    public function rules()
    {
        return [
            [['name', 'email'], 'required'],
            ['email', 'email'],
        ]; // TODO: Change the autogenerated stub
    }
}

?>