<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/1/10
 * Time: 14:27
 */

namespace app\models;


use yii\base\Model;

class Weather extends Model
{
    public $area;
    public function rules()
    {
        return [
            [['area'], 'required'],
        ]; // TODO: Change the autogenerated stub
    }
}